# Generated by Django 3.0.1 on 2019-12-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRIScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50, unique=True)),
                ('t1', models.FileField(upload_to='scans')),
                ('t1ce', models.FileField(upload_to='scans')),
                ('t2', models.FileField(upload_to='scans')),
                ('flair', models.FileField(upload_to='scans')),
            ],
        ),
    ]
